FNP-55 Add Service Worker and Enhance Project Setup
friday-night-push/blockhaus pull request #60
Opened 2024-08-09 19:53 UTC by khizrim

- Service Worker Implementation: Registered the Service Worker and added caching logic for offline support.
- Refactored Code: Improved type inference with a generic type parameter in getResponseOrThrow. Removed unused SVG files and outdated re-exports for cleaner code.
- Project Configuration: Updated .eslintignore to exclude build directories, adjusted TypeScript configuration for better type management, and set informative meta tags in index.html.

2024-08-10 18:01 UTC, Libarus approved these changes

2024-08-11 00:45 UTC, kyzinatra commented on packages/client/src/service-worker.ts
> +  '/profile',
Надо исправить: сейчас вы кэшируете 5 одинаковых файлов, так как на все эти страницы сервер отдает один и тот же html файл. Он и будет закэширован. При этом не будут закэшированны css и js файлы, без которых работа SPA невозможна. Сейчас эти файлы кэшируются через обработчик `fetch`. Поэтому может казаться, что все работает, но так их невозможно нормально инвалидировать и контролировать. Стоит использовать обработчик `fetch` для хранения и переотправки наших запросов.

Стоит прописать всю статику в `PRECACHE_URLS` (картинки,css,js,html). Для этого можно сделать либо свой скрипт, который берет все названия из билда, или использовать готовые решения, которые делают это самостоятельно

2024-08-11 00:45 UTC, kyzinatra commented on packages/client/src/service-worker.ts
> +      .then(cache =>
Кэширование fetch реализовано хорошо

2024-08-11 00:46 UTC, kyzinatra requested changes
Отличная работа над service worker. Но к сожалению сейчас есть проблема с тем, что `.then(cache => cache.addAll(PRECACHE_URLS))` не работает так, как это ожидается. Стоит поправить его работу и проект будет принят!

2024-08-12 04:50 UTC, khizrim commented on packages/client/src/service-worker.ts
> +  '/profile',
Можно использовать [Vite PWA](https://vite-pwa-org.netlify.app/workbox/generate-sw.html) и [Workbox](https://web.dev/learn/pwa/workbox) вместо собственной реализации?

2024-08-12 08:40 UTC, kyzinatra commented on packages/client/src/service-worker.ts
> +  '/profile',
Конечно!

2024-08-14 00:52 UTC, kyzinatra approved these changes
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-08-19 14:07 UTC, merged